name: Build and Deploy CSJ React POC

on:
 
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  APP_NAME: 'app-sj311react-poc-test'

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build React app
        run: npm run build

      - name: Add production startup file
        run: |
          echo '{ "scripts": { "start": "pm2 serve /home/site/wwwroot --no-daemon --spa" }, "dependencies": { "pm2": "latest" } }' > dist/package.json

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          
      - name: Deploy to CSC App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: Production
          package: ./dist
